name: material2_dart
description: angular/material2 for Dart.
version: 0.4.1
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/material2_dart
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  http: ">=0.11.0 <0.12.0"
  stack_trace: ">=1.6.6 <2.0.0"
  stream_transformers: ">=0.3.0 <0.4.0"
  quiver:  ^0.24.0
dev_dependencies:
  browser: <0.10.0
  test: '>=0.12.0 <0.13.0'
  build: ^0.4.0
  sass_builder:
    git:
     url: git@github.com:ntaoo/sass_builder.git
     ref: master
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
- test/pub_serve:
    $include: test/**_test{.*,}.dart