name: material2_dart
description: angular/material2 for Dart.
version: 0.1.1
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/material2_dart
environment:
  sdk: '>=1.16.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.21
  http: ">=0.11.0 <0.12.0"
  stack_trace: ">=1.6.6 <2.0.0"
  stream_transformers: ">=0.3.0 <0.4.0"
  quiver:  ^0.22.0
  scissors: 0.6.4
dev_dependencies:
  browser: <0.10.0
  test: '>=0.12.0 <0.13.0'
transformers:
- scissors:
    pruneCss: false
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
- test/pub_serve:
    $include: test/**_test{.*,}.dart